{% set name = "kalmangrad" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kalmangrad-{{ version }}.tar.gz
  sha256: f4e07125d31034b48b37d153c2efba789e1283221f33fc5a0e57e3f40232c809

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - bayesfilter

test:
  imports:
    - kalmangrad
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hugohadfield/kalmangrad
  summary: Automated, smooth, N'th order derivatives of non-uniformly sampled time series data
  license: MIT
  license_file: licence.txt

extra:
  recipe-maintainers:
    - thewchan
